// apps/web/src/lib/components/popus/SaveDialog.svelte
<!--
    /* Copyright (C) 2026 Illindala Karthik Saiharsh - All Rights Reserved
     * You may use, distribute and modify this code under the
     * terms of the GPL V3 license.
     * I would prefer it if you provide credits, in case you use my code for your projects :)
     */ 
-->

<script lang="ts">
    import ProjectClass from "../../brain/store.svelte";
    import * as Card from "../ui/card/index";
    import Button from "../ui/button/button.svelte";
    import { X, Download, ImageDown } from "@lucide/svelte";

    let { stage } = $props();

    let export_scale = $state("1x");
    const togglers = ProjectClass.togglers;

    function handleCancel() {
        togglers.show_save_details = false;
    }

    function saveProject() {
        ProjectClass.exportProject();
        handleCancel();
    }

    function downloadImage() {
        if (!stage?.node) return;

        const pixelRatio = Number.parseInt(export_scale, 10);

        const dataUrl = stage.node.toDataURL({
            mimeType: "image/png",
            pixelRatio,
        });

        const link = document.createElement("a");
        link.href = dataUrl;
        link.download = `${ProjectClass.project_details.name}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        handleCancel();
    }
</script>

{#if togglers.show_save_details}
    <main
        class="absolute top-0 left-0 z-20 flex justify-center items-center w-screen h-screen bg-background/10 backdrop-blur">
        <Card.Root
            class={`-my-4 w-full max-w-sm shadow-[0px_0px_50px_0px_#000000${ProjectClass.theme === "dark" ? "85" : "25"}]`}>
            <Card.Header>
                <Card.Title class="font-geist">Save Project</Card.Title>
                <Card.Description class="font-geist"
                    >Save or export your project</Card.Description>
                <Card.Action onclick={handleCancel}>
                    <Button variant="link" size="icon"><X /></Button>
                </Card.Action>
            </Card.Header>

            <Card.Content
                class="flex flex-col justify-center items-center gap-6">
                <section class="w-full flex flex-col gap-3">
                    <h3 class="font-geist text-base font-semibold">
                        Save Project as File
                    </h3>
                    <Button class="w-full" onclick={saveProject}>
                        <Download />
                        Download
                    </Button>
                </section>

                <section class="w-full flex flex-col gap-3">
                    <h3 class="font-geist text-base font-semibold">
                        Export Project as Image
                    </h3>

                    <div class="flex w-full items-center gap-3">
                        <select
                            class="h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                            bind:value={export_scale}>
                            <option value="1x">1x</option>
                            <option value="2x">2x</option>
                            <option value="3x">3x</option>
                        </select>

                        <Button class="shrink-0" onclick={downloadImage}>
                            <ImageDown />
                            Download Image
                        </Button>
                    </div>
                </section>
            </Card.Content>

            <Card.Footer class="flex justify-center items-center">
                <Button onclick={handleCancel} variant="secondary"
                    >Close</Button>
            </Card.Footer>
        </Card.Root>
    </main>
{/if}

// src/components/SaveDialog.jsx
import { useAtom, useAtomValue } from "jotai";
import { HardDriveDownload, X } from "lucide-react";
import { useState } from "react";
import { editor_state, layer_ref } from "../lib/stores";

const SaveDialog = () => {
	const [EditorState, setEditorState] = useAtom(editor_state);
	const LayerRef = useAtomValue(layer_ref);

	const [saveDetails, setSaveDetails] = useState({
		name: "",
		resolution: 2,
	});

  return (
    <div
      className={`absolute left-0 w-screen h-15 flex justify-center transition-all ease-in-out duration-550 ${EditorState == "Save FSM" ? "top-8" : "-top-20 opacity-0"
        }`}
    >
      <div className="h-full w-fit px-2 bg-primary-bg rounded-xl border-1 border-border-bg shadow-[0px_0px_50px_0px_#00000080] flex justify-center items-center gap-3">
        <input
          value={saveDetails.name}
          className="px-1 py-2 text-sm h-9 w-full font-medium text-white font-github rounded-lg border border-border-bg outline-none hover:border-white/30 focus:border-blue-500 transition-all ease-in-out"
          type="text"
          placeholder="Enter File Name..."
          onChange={(e) =>
            setSaveDetails({ ...saveDetails, name: e.target.value })
          }
        />

				<select
					value={saveDetails.resolution}
					onChange={(e) =>
						setSaveDetails({ ...saveDetails, resolution: e.target.value })
					}
					className="text-white font-github text-base px-2 border border-border-bg hover:border-input-active focus:border-2 focus:border-blue-500 transition-all ease-in-out outline-none h-9 rounded-lg mr-2"
				>
					<option value={1}>1x</option>
					<option value={2}>2x</option>
					<option value={3}>3x</option>
					<option value={4}>4x</option>
					<option value={5}>5x</option>
				</select>

        <button
          onClick={() => setEditorState(null)}
          className="flex items-center justify-center gap-2 bg-secondary-fg w-fit px-2 py-2 rounded-lg cursor-pointer hover:scale-105 active:scale-95 transition-all ease-in-out"
        >
          <X size={18} color="#000000" />
          <p className="text-sm font-semibold text-black font-github">Cancel</p>
        </button>

				<button
					type="button"
					onClick={() => {
						// Save the FSM to disk

						if (saveDetails.name.trim() === "") {
							alert("Enter a valid file name");
							return;
						}

						const group = LayerRef.findOne("Group");
						const dataUrl = group.toDataURL({
							pixelRatio: saveDetails.resolution, // Resolution
						});

						const link = document.createElement("a");

						link.download = saveDetails.name;
						link.href = dataUrl;
						document.body.appendChild(link);
						link.click();
						document.body.removeChild(link);

            setEditorState(null);
            setSaveDetails({ name: "", resolution: 2 });
          }}
          className="flex items-center justify-center gap-2 bg-blue-500 w-fit px-2 py-2 rounded-lg cursor-pointer hover:scale-105 active:scale-95 transition-all ease-in-out"
        >
          <HardDriveDownload size={18} color="#ffffff" />
          <p className="text-sm font-semibold text-white font-github">Save</p>
        </button>
      </div>
    </div>
  );
};

export default SaveDialog;
