// src/components/Dock.tsx
import {
  MousePointer2,
  PlusCircleIcon,
  MinusCircleIcon,
  Hand,
} from "lucide-react";
import clsx from "clsx";
import { editorState } from "../lib/backend";
import { useAtomValue, useSetAtom } from "jotai";

const Dock = () => {
  const DockIconSize = 24;
  const DockIconColor = "#ffffff";

  // Global editor state store
  const currentState = useAtomValue(editorState);
  const setCurrentState = useSetAtom(editorState);

  return (
    <div className="absolute bottom-5 w-screen h-15 flex justify-center items-center">
      <div className="w-100 h-15 z-10 bg-secondary-bg rounded-2xl border border-border-bg flex justify-center items-center gap-5 shadow-[0px_0px_40px_0px_rgba(0,0,0,0.5)]">
        {/* Dock Items */}

        {/* Grab/Move Editor */}
        <div
          onClick={() =>
            currentState == "grab"
              ? setCurrentState("nil")
              : setCurrentState("grab")
          }
          className={clsx(
            "p-2 border border-border-bg rounded-xl hover:scale-130 hover:-translate-y-5 active:scale-100 cursor-pointer transition-all ease-in-out duration-300",
            {
              "bg-secondary-bg": currentState != "grab",
              "bg-blue-500": currentState == "grab",
            }
          )}
        >
          <Hand
            size={DockIconSize}
            color={DockIconColor}
            className="pointer-events-none"
          />
        </div>

        {/* Select/Move Nodes */}
        <div
          onClick={() =>
            currentState == "select"
              ? setCurrentState("nil")
              : setCurrentState("select")
          }
          className={clsx(
            "p-2 border border-border-bg rounded-xl hover:scale-130 hover:-translate-y-5 active:scale-100 cursor-pointer transition-all ease-in-out duration-300",
            {
              "bg-secondary-bg": currentState != "select",
              "bg-blue-500": currentState == "select",
            }
          )}
        >
          <MousePointer2
            size={DockIconSize}
            color={DockIconColor}
            className="pointer-events-none"
          />
        </div>

        {/* Create Node */}
        <div
          onClick={() =>
            currentState == "create"
              ? setCurrentState("nil")
              : setCurrentState("create")
          }
          className={clsx(
            "p-2 border border-border-bg rounded-xl hover:scale-130 hover:-translate-y-5 active:scale-100 cursor-pointer transition-all ease-in-out duration-300",
            {
              "bg-secondary-bg": currentState != "create",
              "bg-blue-500": currentState == "create",
            }
          )}
        >
          <PlusCircleIcon
            size={DockIconSize}
            color={DockIconColor}
            className="pointer-events-none"
          />
        </div>

        {/* Delete Node */}
        <div
          onClick={() =>
            currentState == "delete"
              ? setCurrentState("nil")
              : setCurrentState("delete")
          }
          className={clsx(
            "p-2 border border-border-bg rounded-xl hover:scale-130 hover:-translate-y-5 active:scale-100 cursor-pointer transition-all ease-in-out duration-300",
            {
              "bg-secondary-bg": currentState != "delete",
              "bg-blue-500": currentState == "delete",
            }
          )}
        >
          <MinusCircleIcon
            size={DockIconSize}
            color={DockIconColor}
            className="pointer-events-none"
          />
        </div>

        {/* Dock Items */}
      </div>
    </div>
  );
};

export default Dock;

// src/lib/components/Dock.svelte
<script>
    // @ts-ignore
    import { MousePointer2, CirclePlus, CircleMinus } from '@lucide/svelte';

    const hoverScale = '130';
    const yTransDist = '10';
</script>

<div class="absolute bottom-2 z-10 flex h-20 w-full items-center justify-center">

	<div class="h-15 w-100 rounded-2xl border border-fourth bg-secondary flex justify-center items-center gap-5 shadow-[0px_0px_50px_0px_rgba(0,0,0,0.3)]">


        <p class={`bg-fourth p-2 rounded-full cursor-pointer hover:scale-${hoverScale} hover:mb-${yTransDist} active:scale-100 transition-all ease-in-out duration-300`}>
            <MousePointer2 size={25}  color="#ffffff"/>
        </p>

        <p class={`bg-fourth p-2 rounded-full cursor-pointer hover:scale-${hoverScale} hover:mb-${yTransDist} active:scale-100 transition-all ease-in-out duration-300`}>
            <CirclePlus size={25}  color="#ffffff"/>
        </p>

        <p class={`bg-fourth p-2 rounded-full cursor-pointer hover:scale-${hoverScale} hover:mb-${yTransDist} active:scale-100 transition-all ease-in-out duration-300`}>
            <CircleMinus size={25}  color="#ffffff"/>
        </p>

    </div>
</div>
